import Link from "next/link";
import Image from "next/image";
import { Icon } from "@/components/icon";
import { QuotePicker } from "@/components/quote-picker";
import { agency, services, faqs } from "@/lib/content";

export default function Home() {
  return <>
    <section className="hero"><div className="container hero-grid"><div className="hero-copy"><p className="eyebrow"><span className="little-line" /> YOUR TEXAS INDEPENDENT INSURANCE AGENCY</p><h1>Life happens.<br />We’ve got you<br /><em>covered.</em></h1><p className="hero-description">Your home. Your family. Your next big thing.<br className="desktop-break" /> We help protect what matters—with more choices<br className="desktop-break" /> and a real person in your corner.</p><QuotePicker /><div className="hero-reassurance"><span><Icon name="check" size={16} /> Independent advice</span><span><Icon name="check" size={16} /> Personal service</span><span><Icon name="check" size={16} /> Texas-wide</span></div></div><div className="hero-visual"><div className="photo-wrap"><Image className="hero-photo" src="/austin-skyline.jpg" alt="Austin’s skyline and Lady Bird Lake at sunset" fill priority sizes="(max-width: 800px) 100vw, 50vw" /><div className="photo-shade" /><div className="photo-label"><Icon name="pin" size={17} /> AT HOME IN CENTRAL TEXAS</div><div className="photo-message">Big Texas dreams.<br />A little more peace of mind.</div></div><div className="local-card"><div className="local-icon"><Icon name="shield" size={29} /></div><div><strong>Local roots. Real protection.</strong><span>Your neighbors in Round Rock, TX.</span></div></div><div className="image-caption">Austin, Texas <span>•</span> Proudly serving the Lone Star State</div></div></div></section>

    <section className="partner-section" aria-label="Insurance carrier partners"><div className="container partner-inner"><div className="partner-intro">One local agency.<br /><strong>A world of options.</strong></div><div className="partner-logos"><span className="progressive">PROGRESSIVE</span><span className="travelers">Travelers<span className="partner-mark">◠</span></span><span className="safeco">Safeco<span className="partner-sub">INSURANCE</span></span><span className="liberty">Liberty Mutual<span className="partner-sub">INSURANCE</span></span><span className="foremost">FOREMOST<span className="partner-sub">INSURANCE GROUP</span></span></div></div></section>

    <section className="coverage-section section" id="coverage"><div className="container"><div className="section-heading"><div><p className="eyebrow">COVERAGE FOR YOUR EVERYDAY. AND YOUR WHAT-IFS.</p><h2>Whatever life looks like,<br />there’s coverage for it.</h2></div><p>Life doesn’t come in one size.<br />Your insurance shouldn’t either.</p></div><div className="coverage-grid">{services.slice(0, 4).map((s, i) => <Link className="coverage-card" href={`/insurance/${s.slug}/`} key={s.slug}><span className={`coverage-icon icon-tone-${i}`}><Icon name={s.icon} size={30} /></span><h3>{s.name}</h3><p>{s.description}</p><span className="text-link">Explore coverage <span className="link-dot">+</span></span></Link>)}</div><div className="more-coverage"><span>More of life to protect?</span>{services.slice(4).map(s => <Link href={`/insurance/${s.slug}/`} key={s.slug}><Icon name={s.icon} size={18} />{s.name}</Link>)}</div></div></section>

    <section className="about-section section" id="about"><div className="container about-grid"><div className="about-statement"><p className="eyebrow">YOUR NEIGHBOR. YOUR ADVOCATE.</p><h2>Big on choices.<br />Bigger on<br /><em>looking out for you.</em></h2><p>Insurance can feel complicated. Having someone who knows your name—and takes time to understand your life—makes all the difference.</p><a className="button button-navy" href={agency.telephone}>Let’s get to know you</a><div className="about-note"><Icon name="pin" size={18} /> Based in Round Rock. Here for all of Texas.</div></div><div className="benefits"><div className="benefit"><span className="benefit-number">01</span><div><h3>More options. Your choice.</h3><p>We work with multiple insurance companies, so you can explore options that fit your needs, instead of settling for a single carrier.</p></div><Icon name="compare" size={26} /></div><div className="benefit"><span className="benefit-number">02</span><div><h3>Real people, right here.</h3><p>One-on-one service from a local team. We listen, explain your options, and help you make a decision with confidence.</p></div><Icon name="heart" size={26} /></div><div className="benefit"><span className="benefit-number">03</span><div><h3>Here beyond the quote.</h3><p>From a new home to a growing business, we’re here to help you revisit your coverage as your life changes.</p></div><Icon name="support" size={26} /></div></div></div></section>

    <section className="process-section section"><div className="container"><div className="center-heading"><p className="eyebrow">LESS GUESSWORK. MORE CONFIDENCE.</p><h2>Your next chapter starts here.</h2><p>A little conversation can go a long way.</p></div><div className="process-grid"><div className="process-step"><span>01</span><h3>Tell us about your life.</h3><p>A home, a vehicle, a business, or your family. We start with what matters to you.</p></div><div className="process-step"><span>02</span><h3>Explore your options.</h3><p>We help you compare carriers and make sense of the coverage available to you.</p></div><div className="process-step"><span>03</span><h3>Move forward confidently.</h3><p>Choose with guidance from a real person, and keep us in your corner as life changes.</p></div></div><div className="center-actions"><Link className="button button-orange" href="/quote/">Let’s find your coverage</Link><span>No pressure. Just a helpful conversation.</span></div></div></section>

    <section className="client-banner"><div className="container client-banner-inner"><div className="client-banner-title"><span className="client-banner-icon"><Icon name="document" size={29} /></span><div><p className="eyebrow">ALREADY PART OF THE CENTEX FAMILY?</p><h2>A little help, whenever you need it.</h2><p>Find policy documents, ID cards, and carrier support in one place.</p></div></div><Link className="button button-white" href="/client-center/">Visit the client center</Link></div></section>

    <section className="faq-section section" id="faq"><div className="container faq-grid"><div><p className="eyebrow">A FEW THINGS YOU MAY BE WONDERING</p><h2>Good questions.<br />Straight answers.</h2><p>Can’t find what you’re looking for?<br />We’re always happy to talk it through.</p><a className="faq-phone" href={agency.telephone}><Icon name="phone" size={19} />{agency.phone}</a></div><div className="faq-list">{faqs.map(f => <details key={f.question}><summary>{f.question}<span className="faq-plus">+</span></summary><p>{f.answer}</p></details>)}</div></div></section>

    <section className="contact-section section" id="contact"><div className="container contact-grid"><div><p className="eyebrow">LET’S TALK ABOUT WHAT MATTERS</p><h2>Your next step?<br /><em>A real conversation.</em></h2><p>Whether you’re comparing coverage or need a little help with your policy, your local Centex team is here.</p><div className="contact-buttons"><Link className="button button-orange" href="/quote/">Get a free quote</Link><a className="button button-outline" href={agency.contact} target="_blank" rel="noopener noreferrer">Send us a message</a></div></div><div className="contact-card"><div><span className="contact-icon"><Icon name="phone" size={22} /></span><div><span className="small-label">GIVE US A CALL</span><a className="contact-main" href={agency.telephone}>{agency.phone}</a><p>Option 1: New quotes · Option 2: General inquiries</p></div></div><div><span className="contact-icon"><Icon name="mail" size={22} /></span><div><span className="small-label">DROP US A LINE</span><a className="contact-main" href={`mailto:${agency.email}`}>{agency.email}</a></div></div><div><span className="contact-icon"><Icon name="pin" size={22} /></span><div><span className="small-label">YOUR LOCAL AGENCY</span><a href={agency.map} target="_blank" rel="noopener noreferrer">{agency.address}<br />{agency.city}</a></div></div></div></div></section>
  </>;
}
