import type { Metadata } from "next";
import Link from "next/link";
import { agency } from "@/lib/content";

export const metadata: Metadata = { title: "Privacy & website information" };

export default function PrivacyPage() {
  return <><section className="page-hero"><div className="container"><nav className="breadcrumb" aria-label="Breadcrumb"><Link href="/">Home</Link><span>/</span><span>Website information</span></nav><p className="eyebrow">CLEAR AND SIMPLE</p><h1>Privacy & website information.</h1><p className="lead">A few details about this website and the services it links to.</p></div></section><section className="section"><div className="container privacy-copy"><h2>Information on this website</h2><p>This website presents general information about Centex Insurance Solutions and available insurance topics. It does not provide a quote, bind coverage, or modify an existing policy. Your insurer’s policy documents determine coverage, limitations, and exclusions.</p><h2>Quote requests and client services</h2><p>Quote, contact, client portal, and carrier links direct you to Centex’s existing website or another service. Any information you submit there is handled by that service under its own policies. This website does not include a local quote submission form or client login.</p><h2>External resources</h2><p>Phone and email links open the corresponding application on your device. Map links open Google Maps. The site’s typography is provided by Google Fonts; your browser may contact Google to retrieve those font files.</p><h2>Questions</h2><p>For questions about your insurance or how Centex handles information submitted through its services, contact <a href={`mailto:${agency.email}`}>{agency.email}</a> or call <a href={agency.telephone}>{agency.phone}</a>.</p></div></section></>;
}
