import type { Metadata } from "next";
import Link from "next/link";
import { agency } from "@/lib/content";

export const metadata: Metadata = { title: "Privacy & website information" };

export default function PrivacyPage() {
  return <><section className="page-hero"><div className="container"><nav className="breadcrumb" aria-label="Breadcrumb"><Link href="/">Home</Link><span>/</span><span>Website information</span></nav><p className="eyebrow">CLEAR AND SIMPLE</p><h1>Privacy & website information.</h1><p className="lead">A few details about this website and the services it links to.</p></div></section><section className="section"><div className="container privacy-copy"><h2>Information on this website</h2><p>This website presents general information about Centex Insurance Solutions and available insurance topics. It does not provide a quote, bind coverage, or modify an existing policy. Your insurer’s policy documents determine coverage, limitations, and exclusions.</p><h2>Quote requests</h2><p>When online requests are enabled, our quote form collects your name, email address, phone number, ZIP code, requested insurance type, comments, and permission to contact you. We use this information to respond to your request. The website processes submissions through Vercel and sends them to the Centex team through Microsoft 365. Messages are retained in agency mailboxes according to agency practices; this website does not add a separate quote database or save form entries in browser storage. Please do not include Social Security numbers, payment information, or sensitive documents.</p><h2>Client services and external links</h2><p>The EZLynx client portal, carrier websites, and other external services handle information submitted to them under their own policies. The website does not provide a local customer login. For questions about access, correction, deletion, or retention of information you submit, contact the agency below.</p><h2>External resources</h2><p>Phone and email links open the corresponding application on your device. Map links open Google Maps. The site’s typography is provided by Google Fonts; your browser may contact Google to retrieve those font files.</p><h2>Questions</h2><p>For questions about your insurance or how Centex handles information submitted through its services, contact <a href={`mailto:${agency.email}`}>{agency.email}</a> or call <a href={agency.telephone}>{agency.phone}</a>.</p></div></section></>;
}
